#base setting
server:
  port: 8090

#log setting
logging:
  file: ./log/ShiroApplication.log
  level:
    root: info

#dagasource and jpa setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

#JWT setting
secretKey: qwertyuiopasdfghjklzxcvbnm