#base setting
server:
  port: 8090

#log setting
logging:
  file: ./log/ShiroApplication.log
  level:
    root: info

#dagasource and jpa setting
spring:
  datasource:
#    公司电脑配置useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    公司电脑配置
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: update
    showSql: true

#JWT setting
secretKey: qwertyuiopasdfghjklzxcvbnm